server:
  port: ${PORT_APP:8081}
  servlet:
    context-path: /modelhealth

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,default
      probes:
        enabled: true #liveness and #readiness
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics,prometheus'

## Configuring info endpoint
info:
  app:
    name: 'Health Sample Application'
    description: 'This is health spring boot application'
    version: 1.0.0
    vendor: ${java.specification.vendor}

service:
  default:
    url: 'http://localhost:8082/gigatest'